### ISSUE TITLE
Ability to create color profiles

### ISSUE THREAD

**Issue by fsobolev** [fsobolev/cavalier#12]
Add ability to create multiple profiles for colors and switch between them.

**Comment by ghost** [comment]
Maybe one could use a color profile list instead of where you set the colors now. There could be a "New profile" button which would then be where you can set the colors.

**Comment by fsobolev** [comment]
My plan is to add Gtk.DropDown and 2 buttons to add and remove profile to the suffix of colors Adw.PreferencesGroup. When a user selects profile from dropdown, colors grid changes.

**Comment by ghost** [comment]
Where would those add/ remove buttons be located?

Also, wouldn't a list be better than a dropdown?

**Comment by fsobolev** [comment]
> Where would those add/ remove buttons be located?

Next to the dropdown, in the suffix. It will be a Gtk.Box there that will contain dropdown, + button and - button.

> Also, wouldn't a list be better than a dropdown?

I will think more about it, but currently I think it will use too much space: either the colors grid will be under the list of profiles and a user will need to scroll down if the are more than 1 profile, or the grid will be opened in a dialog after clicking on a profile. Both options require additional actions from user to access color grid.

**Comment by fsobolev** [comment]
![](https://i.imgur.com/MQ7bqPj.png)

Dropdown contains a list of existing profiles. There's a always a "Default" profile that can't be removed. Buttons open popovers to confirm adding/removing a profile. Adding a profile requires to set a name for it (there's an entry in popover) that must be unique, after creation a new profile will be a copy of an active profile.
