### ISSUE TITLE
Increase max line thickness

### ISSUE THREAD

**Issue by ghost** [fsobolev/cavalier#23]
In the next-branch, the line thickness of Line mode can be set to a maximum of 30 pixels. I've been experimenting a bit, and in maximized window state, 40 pixels still looks good, and 50 looks acceptable. I'm wondering if we should set the max line thickness to 50 px instead of 30, or leave it as is.

[Kooha-2023-01-29-11-08-22 (trimmed).webm](https://user-images.githubusercontent.com/119804311/215319650-e7c253ef-3fe1-4d05-a2ce-3b267b76ff2b.webm)

**Comment by fsobolev** [comment]
I see the difference between 30 and 40 and I like how 40 looks both in maximized window and in small window where it can give kinda "jumping cloud" effect. Difference between 40 and 50 is not that noticeable, and increasing range makes it harder to set precise value on slider in preferences window using mouse, so I would prefer to set maximum value to 40.
