### ISSUE TITLE
Elements get squished in streched window

### ISSUE THREAD

**Issue by ghost** [fsobolev/cavalier#28]
[Kooha-2023-01-30-11-00-07.webm](https://user-images.githubusercontent.com/119804311/215446477-ecee612c-e825-4146-bf34-6f4020a8f3ae.webm)

In Particles and Levels mode, the elements get thinner the wider the window is. After a certain point in wideness, they start reappearing.

**Comment by ghost** [comment]
It doesn't seem to affect Spine mode

**Comment by fsobolev** [comment]
In Spine mode elements have fixed aspect ratio (so with 0 Roundness they are always perfect squares), but in other modes it's different. I guess it's needed to somehow limit minimal size to avoid elements disappearing.
