### ISSUE TITLE
Merge Line & Wave into one

### ISSUE THREAD

**Issue by ghost** [fsobolev/cavalier#38]
I'm working on an option to fill in items or not, and I noticed we could implement that for Line & Wave too, so there would only be Wave mode, and if you turn off filling in items, it turns into Line. @fsobolev what do you think of this idea?

**Comment by ghost** [comment]
I opened a PR, so this discussion will be continued in #39 .

**Comment by fsobolev** [comment]
It's better to keep this issue opened until we decide if it will be implemented.
