### ISSUE TITLE
Import / Export issue 

### ISSUE THREAD

**Issue by dasnoopy** [fsobolev/cavalier#44]
Hi,  trying the app, compiled from git [AUR](https://aur.archlinux.org/packages/cavalier-git), I noticed an issue with Import/export

- Import button simply does nothing  (no messages starting app from terminal)
- using Export button this windows appear
![image](https://user-images.githubusercontent.com/296922/216898676-a384c304-f296-480b-a292-a7a5f9a77595.png)
in addition, from terminal this warning appear at the same time : 
$`GtkDialog mapped without a transient parent. This is discouraged.`

Some further details:
- Archlinux 64bit
- Gnome 42.3 on **Wayland**
- GTK4 4.8.3
- libadwaita 1.2.1

Regards
Andrea

**Comment by fsobolev** [comment]
Can reproduce it after building without flatpak, will try to fix.

**Comment by fsobolev** [comment]
For some reason, Gtk.FileChooserNative fails outside of flatpak. Current workaround is to use Gtk.FileChooserDialog when not running in flatpak. It looks the same, except Open/Save button doesn't use accent color, and some strings are not translated (like "Other locations"), which is weird, but anyway, at least it works. Both dialog widgets are deprecated and will be replaced by [Gtk.FileDialog](https://docs.gtk.org/gtk4/class.FileDialog.html) in future, I hope it will solve all problems.
