### ISSUE TITLE
Make keyboard shortcuts follow GNOME HIG

### ISSUE THREAD

**Issue by ghost** [fsobolev/cavalier#46]
The GNOME HIG recommend using `Ctrl`+`,` for opening the app settings. https://developer.gnome.org/hig/reference/keyboard.html

**Comment by fsobolev** [comment]
`Ctrl+W` should close the window as well, and `F10` should open the menu

**Comment by ghost** [comment]
> `Ctrl+W` should close the window as well, and `F10` should open the menu

I'm not so sure about `Ctrl+W`, because we already have `Ctrl+Q` for that. I think `Ctrl+W` is for closing things like tabs, whereas `Ctrl+Q` is for closing the app.

**Comment by fsobolev** [comment]
> > `Ctrl+W` should close the window as well, and `F10` should open the menu
> 
> I'm not so sure about `Ctrl+W`, because we already have `Ctrl+Q` for that. I think `Ctrl+W` is for closing things like tabs, whereas `Ctrl+Q` is for closing the app.

From the HIG:

> Close | Ctrl+W | Closes the current tab or window.

In tabbed or multi-window interface this should close currently active tab or window, but in single-window tabless app I suppose it should close the window just like `Ctrl+Q`. Anyway, I don't see a problem in having 2 shortcuts for the same action.

**Comment by ghost** [comment]
How about `F11` for fullscreen? (Not in GNOME HIG, but wide-spread practice, Apostrophe does it for instance)

**Comment by ghost** [comment]
![Screenshot from 2023-02-27 17-20-48](https://user-images.githubusercontent.com/119804311/221619939-3b800012-ab80-4c80-b4c9-23c426744309.png)

I implemented these shortcuts. Unfortunately, it's not possible to close the menu by pressing `F10` a second time, one has to use `Esc` for that. 

Also, is the order in the picture okay for displaying in the shortcuts window?

**Comment by fsobolev** [comment]
Ctrl+W should be next to Ctrl+Q for Quit, because this is what it does, making it a separate shortcut with such label can confuse users by making them think that Cavalier can either run in multiple windows or run in the background without a window doing something.
The order is fine.

> Unfortunately, it's not possible to close the menu by pressing F10 a second time, one has to use Esc for that.

The HIG only says about opening the menu, so this is not a problem.

Thanks

**Comment by ghost** [comment]
> Ctrl+W should be next to Ctrl+Q for Quit, because this is what it does, making it a separate shortcut with such label can confuse users by making them think that Cavalier can either run in multiple windows or run in the background without a window doing something. The order is fine.
> 
> > Unfortunately, it's not possible to close the menu by pressing F10 a second time, one has to use Esc for that.
> 
> The HIG only says about opening the menu, so this is not a problem.
> 
> Thanks

Only the way I implemented it right now makes the app close *only* the active window. If that happens to be the main window, the it closes the app entirely. Unlike the current function of `Ctrl`+`Q`, which closes the entire app no matter what the active window is.

**Comment by fsobolev** [comment]
> Only the way I implemented it right now makes the app close _only_ the active window. If that happens to be the main window, the it closes the app entirely. Unlike the current function of `Ctrl`+`Q`, which closes the entire app no matter what the active window is.

Ah, okay, let it be like this then :)

**Comment by ghost** [comment]
> How about `F11` for fullscreen? (Not in GNOME HIG, but wide-spread practice, Apostrophe does it for instance)

@fsobolev Any opinion on this?

**Comment by ghost** [comment]
It seems the order of the shortcuts in the help overlay is actually determined anywhere, and is inconsistent among other GNOME apps. I might reorder them anyhow, because the current way doesn't seem very intuitive to me (personally).

**Comment by fsobolev** [comment]
> @fsobolev Any opinion on this?

I agree, `F11` would be nice to have too
