### ISSUE TITLE
app starting errors after update gtk4 pkg to vers 4.10 on archlinux

### ISSUE THREAD

**Issue by dasnoopy** [fsobolev/cavalier#49]
not sure about the main cause but on archlinux  after recent GTK4 package update from vers. 4.8.3 to 4.10.0, the app (compiled from git with [AUR](https://aur.archlinux.org/packages/cavalier-git) pkgbuild), doesn't run correctly: 

starting app from console  following error appears:

```
$cavalier 
Traceback (most recent call last):
  File "/usr/share/cavalier/cavalier/main.py", line 68, in do_activate
    self.win = CavalierWindow(application=self)
  File "/usr/share/cavalier/cavalier/window.py", line 47, in __init__
    self.build_ui()
  File "/usr/share/cavalier/cavalier/window.py", line 64, in build_ui
    self.apply_colors()
  File "/usr/share/cavalier/cavalier/window.py", line 141, in apply_colors
    self.css_provider.load_from_data(self.css_data)
TypeError: Gtk.CssProvider.load_from_data() takes exactly 3 arguments (2 given)
^C
$
```

Thanks in advance
Andrea

**Comment by fsobolev** [comment]
Gtk 4.10 doesn't seem to fully release yet (website states that 4.8.3 is latest stable still, and I can't find a changelog for 4.10), but it seems like `Gtk.CssProvider.load_from_data` was the only thing that needed to be changed, after the latest commit Cavalier works fine for me in Arch distrobox. I tested most of the settings, but if you will find that something breaks the app I will fix it again.

**Comment by fsobolev** [comment]
@bordam Btw, PKGBUILD misses `python-cairo` as dependency (it's make dependency for python-gobject, but Cavalier needs it as runtime dependency too).

**Comment by bordam** [comment]
Ok, I added the dependency.
