### ISSUE TITLE
Ability to change Drawing mode / Preset by keyboard shortcuts

### ISSUE THREAD

**Issue by ghost** [fsobolev/cavalier#9]
Hey, great app and smooth rendering!

I'd like to be able to swap the drawing mode using shortcut without going to preferences, perhaps with L/R arrow keys.
Might make sense to also have shortcuts for other things - like moving the color hue +/- etc.

**Comment by ghost** [comment]
I think maybe "." and "," would be better because they're right next to each other. I think the arrow keys are quite important keys and should be responsible for more important settings. Also, there are 4 arrow keys, so I think they should be reserved for a setting that benefits from that amount of keys.

**Comment by fsobolev** [comment]
I was thinking about something mpv-like: "m" to change to the next mode and "Shift-m" to change to the previous mode. And similar for other settings, but with different buttons (maybe "c" for channels, "r" for roundness, "p" for color profiles, etc).

**Comment by ghost** [comment]
I like that! would it be possible to do something like "r" + "+" and "r" + "-" for changing roundness?

Edit: Forgot you meant "r" and "Shift" + "r", so forget about it.

**Comment by gregorni** [comment]
With the color profiles now merged, we might also want to create a shortcut for swapping between those. I would suggest "p" and "Shift"+" p".

**Comment by fsobolev** [comment]
![](https://i.imgur.com/H9YHJ0D.png)

Most of the settings can now be changed using keyboard shortcuts. Shortcuts dialog is not modal, so you can open it and still have main window active and use shortcuts without closing shortcuts dialog.
When it makes sense, pressing a key increases a value, while Shift+key decreases it. Changing mode or profile goes indefinitely in circle, so for example if you press P when the last profile is active it will change to the first profile.
N is used for Margi`n` because M will be used for Mirror. E is used for R`e`verse because R and O are already in use.

**Comment by ghost** [comment]
Awesome, thanks!

**Comment by ghost** [comment]
I think a setting such a sharp window corners doesn't need 2 keyboard shortcuts, though. It only has two options, so one shortcut to toggle between those two states should be enough, right?

**Comment by fsobolev** [comment]
> I think a setting such a sharp window corners doesn't need 2 keyboard shortcuts, though. It only has two options, so one shortcut to toggle between those two states should be enough, right?

Settings that have only 2 states indeed only require 1 shortcut. I just found it logical to provide `Key / Shift+Key` shortcuts for everything for consistency. But if you think it's excessive I can remove `Shift+Key` shortcuts for such settings.

**Comment by ghost** [comment]
I think if we group the settings the way they are now, with the "Change …" settings listed first and the "Toggle …" settings second, it should be consistent enough.

**Comment by ghost** [comment]
![Screenshot from 2023-01-28 09-33-43](https://user-images.githubusercontent.com/119804311/215255950-8ac5f814-7455-4efb-ad8e-013fbdc53ea6.png)


Hmm. What do you think?

**Comment by fsobolev** [comment]
@gregorni Looks good to me :) To actually remove shortcuts you can remove lines like these in `shortcuts.py`:
```
shortcut_controller.add_shortcut(Gtk.Shortcut.new( \
        Gtk.ShortcutTrigger.parse_string("<Shift>S"), \
        Gtk.NamedAction.new("cavalier.toggle-corners")))
```
Feel free to open a PR 😊

**Comment by ghost** [comment]
Okay, I'll get working on it. Thanks for the tip!

**Comment by fsobolev** [comment]
@gregorni I changed "Change Widgets Style" -> "Toggle Widgets Style", so it's the same as with other 2-state settings and use one shortcut

**Comment by ghost** [comment]
I was about to ask you about that.

**Comment by ghost** [comment]
For consistency it would also be better to have the Toggle Widgets Style listed below the Change Color Profile shortcut.

**Comment by fsobolev** [comment]
> For consistency it would also be better to have the Toggle Widgets Style listed below the Change Color Profile shortcut.

Yeah, I don't mind. I listed shortcuts in the same order as in the preferences window, but I think it's good to make an exception for this one.
